<template>
  <div class="col">
    <v-card>
      <v-btn
        @click.prevent="$router.push('/playlottomain')"
        color="primary"
        elevation="4"
        rounded
        small
        class="ma-2"
      >
        3ตัวบน</v-btn
      >
      <v-btn
        @click.prevent="$router.push('/playlottomain2')"
        color="primary"
        elevation="4"
        rounded
        small
        class="ma-2"
        >2ตัวบน</v-btn
      >
      <v-btn
        @click.prevent="$router.push('/playlottomain1')"
        color="primary"
        elevation="4"
        rounded
        small
        class="ma-2"
        >เลขวิ่งบน</v-btn
      >
      <v-btn
        @click.prevent="$router.push('/playlottomaindown')"
        color="red"
        elevation="4"
        rounded
        small
        class="ma-2"
      >
        3ตัวล่าง</v-btn
      >
      <v-btn
        @click.prevent="$router.push('/playlottomain2down')"
        color="red"
        elevation="4"
        rounded
        small
        class="ma-2"
        >2ตัวล่าง</v-btn
      >
      <v-btn
        @click.prevent="$router.push('/playlottomain1down')"
        color="red"
        elevation="4"
        rounded
        small
        class="ma-2"
        >เลขวิ่งล่าง
      </v-btn>
    </v-card>
  </div>
</template>

<script>
export default {};
</script>

<style></style>
